
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat May 05 22:21:52 ICT 2018
//----------------------------------------------------

package src;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 7;
  public static final int STRING_LITERAL = 37;
  public static final int LTE = 30;
  public static final int LPAREN = 9;
  public static final int SEMI = 2;
  public static final int INT = 21;
  public static final int MINUS = 5;
  public static final int RPAREN = 10;
  public static final int AND = 27;
  public static final int LT = 26;
  public static final int OR = 25;
  public static final int BOOL = 23;
  public static final int COMMA = 3;
  public static final int BEGIN = 19;
  public static final int PLUS = 4;
  public static final int IF = 12;
  public static final int ID = 36;
  public static final int EOF = 0;
  public static final int RETURN = 32;
  public static final int error = 1;
  public static final int MOD = 8;
  public static final int VOID = 31;
  public static final int EQ = 11;
  public static final int GTE = 29;
  public static final int TIMES = 6;
  public static final int ENDIF = 15;
  public static final int ELSE = 14;
  public static final int WHILE = 17;
  public static final int BOL = 33;
  public static final int FLOAT = 22;
  public static final int THEN = 13;
  public static final int END = 20;
  public static final int STRING = 24;
  public static final int FLOAT_LITERAL = 35;
  public static final int GT = 28;
  public static final int PRINT = 16;
  public static final int DO = 18;
  public static final int INTEGER_LITERAL = 34;
}

